# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/karnr/Desktop/COCO/Studios_Labs/Studio4/Studio4.cache/wt [current_project]
set_property parent.project_path C:/Users/karnr/Desktop/COCO/Studios_Labs/Studio4/Studio4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/karnr/Desktop/COCO/Studios_Labs/Studio3/Studio3.srcs/sources_1/new/bit_full_adder.vhd
  C:/Users/karnr/Desktop/COCO/Studios_Labs/Studio4/Studio4.srcs/sources_1/new/XORer.vhd
  C:/Users/karnr/Desktop/COCO/Studios_Labs/Studio4/Studio4.srcs/sources_1/new/ORer.vhd
  C:/Users/karnr/Downloads/Function_select.vhd
  C:/Users/karnr/Downloads/Display_driver.vhd
  C:/Users/karnr/Desktop/COCO/Studios_Labs/Studio4/Studio4.srcs/sources_1/new/ANDer.vhd
  C:/Users/karnr/Desktop/COCO/Studios_Labs/Studio4/Studio4.srcs/sources_1/new/adder.vhd
  C:/Users/karnr/Downloads/LEDdisplay.vhd
  C:/Users/karnr/Desktop/COCO/Studios_Labs/Studio4/Studio4.srcs/sources_1/new/toplevel.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/karnr/Desktop/COCO/Studios_Labs/Studio4/Studio4.srcs/constrs_1/new/ALU.xdc
set_property used_in_implementation false [get_files C:/Users/karnr/Desktop/COCO/Studios_Labs/Studio4/Studio4.srcs/constrs_1/new/ALU.xdc]


synth_design -top toplevel -part xc7a35tcpg236-1


write_checkpoint -force -noxdef toplevel.dcp

catch { report_utilization -file toplevel_utilization_synth.rpt -pb toplevel_utilization_synth.pb }
